### ISSUE TITLE
AM Library portability

### ISSUE THREAD

**Issue by ampetz** [ku-sldg/copland-avm#58]
As of now, JSON AM Library specifications involve fully-qualified pathnames to point to (external to the AM) attestation resources (i.e. ASP executables).  This limits portability across machines.

This task will begin to address AM Library portability by:
- [ ] Supporting relative pathnames in the AM Library 
- [x] Adding command line parameters and/or using environment variables to point to "bins" of ASP executables (and any other AM-external attestation resources).

**Comment by Durbatuluk1701** [comment]
@ampetz This will be closed other than the relative pathnames, I feel like that might not be a viable approach as the relative pathname can change depending on which user is running it and where.

Would be closed by #59
